import os

Import('env')



def recurisveGlob(dir,filter_predicate):
	'''
	filter_predicate should be a function that returns true if the file matches
	dir should be a string of the directory you want to traverse
	ex: lambda a: a.endswith("*cpp")
	'''
	matches = []
	for root, dirnames, filenames in os.walk(dir):
		filtered_matches = filter(filter_predicate,filenames)
		for filename in filtered_matches:
			matches.append(Glob(os.path.join(root,filename)[len(root)+1:]))
		
	
files = recurisveGlob('.', lambda a: a.endswith("*.cpp"))
env.Program('../robot_program',files,libs=['framework'])
